version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: bun run dev

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://db_user:db_password@postgresql:5432/db_name
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - postgres_network_prod

  postgresql:
    image: docker.io/postgres:14
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - "5433:5432"  # Different port for production
    volumes:
      - postgresql_data_prod:/var/lib/postgresql/data
    networks:
      - postgres_network_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
  postgresql_data_prod:

networks:
  postgres_network:
    driver: bridge
  postgres_network_prod:
    driver: bridge