FROM docker.io/oven/bun:1

WORKDIR /usr/src/app

COPY package.json bun.lock ./
RUN bun install

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
ENV DATABASE_URL=postgresql://dev:dev@db:5432/mydb 
EXPOSE 3001

# Combine commands into a single RUN to avoid overwriting 
CMD bun run prisma generate && bun prisma db push  &&  bun run seed:bun && bun run show-env && bun run dev -- -p 3001