name: CI Pipeline

on:
  push:
    branches:
      - main
      # Tu peux ajouter d'autres branches si nécessaire
      # - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js avec la version souhaitée et activer la mise en cache pour pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm globally
        run: npm install -g pnpm@10.6.3
        
 
      # Étape 3 : Installation des dépendances avec pnpm
      - name: Install dependencies with pnpm
        run: pnpm install

      # Étape 4 : Vérification des types TypeScript
      - name: TypeScript type check
        run : turbo telemetry disable && pnpm check-types

      # Étape 5 : Compilation du projet avec turbo
      - name: Build project with turbo
        run: turbo build
