name: Deploy to Netlify

on:
  workflow_dispatch:  # Déclenchement manuel
  # push:            # Décommentez cette section si vous voulez conserver le déploiement automatique
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install 

      - name: Build Next.js app
        run: pnpm turbo run build --filter=rim-ebay

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run:
          echo $NETLIFY_AUTH_TOKEN

          netlify deploy  --filter rim-ebay  --prod --message="Deploy from GitHub Actions"